// This file auto generated by sscli
package client

import (
	"context"
	"fmt"
)

var callerImp caller = &unimpCaller{}

func SetCaller(c caller) {
	callerImp = c
}

type caller interface {
	Call(ctx context.Context, method, path string, req interface{}, rsp interface{}) error
}
type unimpCaller struct{}

func (s *unimpCaller) Call(ctx context.Context, method, path string, req interface{}, rsp interface{}) error {
	return fmt.Errorf("missing caller setting")
}

type SayHelloRequest struct {
	Name string `json:"name"`
}

type SayHelloResponse struct {
	Reply string `json:"reply"`
}

func SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloResponse, error) {
	rsp := &SayHelloResponse{}
	err := callerImp.Call(ctx, "GET", "/api/hello", req, rsp)
	return rsp, err
}
