// This file auto generated by sscli
package client

import (
	"context"
	"fmt"
)

var clientCaller clientInterface = &unimpClient{}

func SetClient(c clientInterface) {
	clientCaller = c
}

type clientInterface interface {
	Call(ctx context.Context, path string, req interface{}, rsp interface{}) error
}

type unimpClient struct{}

func (s *unimpClient) Call(ctx context.Context, path string, req interface{}, rsp interface{}) error {
	return fmt.Errorf("missing caller setting")
}

type HelloServiceSayHelloRequest struct {
	Name string `json:"name"`
}

type HelloServiceSayHelloResponse struct {
	Reply string `json:"reply"`
}

type helloService struct{}

func HelloService() *helloService {
	return &helloService{}
}

func (s *helloService) SayHello(ctx context.Context, req *HelloServiceSayHelloRequest) (*HelloServiceSayHelloResponse, error) {
	rsp := &HelloServiceSayHelloResponse{}
	err := clientCaller.Call(ctx, "/api/HelloService/SayHello", req, rsp)
	return rsp, err
}
